DATASET:
  TRAIN:
    SOURCE_NAME: "SignDataset"
    SOURCE_PATH: "./data/source/sign-all/train"
    TARGET_NAME: "YumiDataset"
    TARGET_PATH: "./data/target/ur3"
  TEST:
    SOURCE_NAME: "SignDataset"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiDataset"
    TARGET_PATH: "./data/target/ur3"
MODEL:
  NAME: "ArmNet"
HYPER:
  EPOCHS: 10
  BATCH_SIZE: 12
  LEARNING_RATE: 0.0001
LOSS:
  EE: False
  VEC: True
  ORI: True
  COL: True
  COL_THRESHOLD: 0.15
  REG: True
OTHERS:
  SAVE: "./saved/models/arm"
  LOG: "./saved/log"
  SUMMARY: "./saved/runs"
  LOG_INTERVAL: 100