DATASET:
  TRAIN:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/train"
    TARGET_NAME: "YumiAll"
    # TARGET_PATH: "./data/target/yushu"
    TARGET_PATH: "./data/target/ur3"
  TEST:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiAll"
    # TARGET_PATH: "./data/target/yushu"
    TARGET_PATH: "./data/target/ur3"
MODEL:
  NAME: "YumiNet"
  # CHECKPOINT: "./saved/models/自制视频/best_model_epoch_0008.pth"
HYPER:
  EPOCHS: 10
  BATCH_SIZE: 12
  LEARNING_RATE: 0.0001
LOSS:
  EE: True
  VEC: True
  ORI: True
  FIN: True
  COL: True
  COL_THRESHOLD: 0.15
  REG: True
  EL: False
OTHERS:
  SAVE: "./saved/models/yumi"
  LOG: "./saved/log/yumi"
  SUMMARY: "./saved/runs/yumi"
  LOG_INTERVAL: 100